---
- hosts: 163.180.118.168
  vars:
        http_port: 80
        max_clients: 200
  # user account
  remote_user: mc-machin01
  become: yes

  #task list
  tasks:
   - name: test connection
     ping:
     become_method: sudo
   - name: apt-get update
     apt:
        update_cache: yes
     become_method: sudo

   - name: Install openvswitch-switch
     apt:
      name: openvswitch-switch
      state: present
     become_method: sudo

   - name: Install openvswitch-common
     apt:
      name: openvswitch-common
      state: present
     become_method: sudo

   - name: Install git
     apt:
      name: git
      state: present
     become_method: sudo

   - name: Wget ovs-docker
     get_url: url=https://raw.githubusercontent.com/openvswitch/ovs/master/utilities/ovs-docker dest=/usr/bin
     become_method: sudo

   - name: Change mode
     file: dest=/usr/bin/ovs-docker mode=a+rwx
