---
#
# Installs ONOS and downloads the related dependencies.
#
- name: Cloning ONOS repository
  git:
    repo: "{{ onos_repo_url }}"
    dest: "{{ onos_dir }}"
    version: "onos-{{ onos_version }}"

- name: Changing ONOS repository permissions
  file:
    path: "/home/ubuntu/onos"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: Exporting ONOS variables
  lineinfile:
    dest: /home/ubuntu/.bashrc
    line: "{{ item }}"
  with_items: "{{ onos_variables }}"

- name: Compiling ONOS
  shell: "{{ item }}"
  args:
    chdir: "/home/ubuntu/onos/tools/build"
  with_items:
    - "./onos-buck build onos"

- name: Creating ONOS deployment script
  template:
    src: templates/onos_deploy.j2
    dest: "/home/ubuntu/onos_deploy.sh"
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: Changing ONOS repository permissions
  file:
    path: "/home/ubuntu/onos"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: Changing /tmp/stc dir permissions
  file:
    path: "/tmp/stc"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0777
