# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.define "m01" do |m01|
    m01.vm.box = "ubuntu/xenial64"
    m01.vm.hostname = "m01"
    m01.vm.network "private_network", ip: "192.180.0.101"
    m01.vm.provider "virtualbox" do |v|
      v.name = "m01"
      v.memory = 4096
    end
  end

  config.vm.define "m02" do |m02|
    m02.vm.box = "ubuntu/xenial64"
    m02.vm.hostname = "m02"
    m02.vm.network "private_network", ip: "192.180.0.102"
    m02.vm.provider "virtualbox" do |v|
      v.name = "m02"
      v.memory = 4096
    end
  end

  config.vm.define "m03" do |m03|
    m03.vm.box = "ubuntu/xenial64"
    m03.vm.hostname = "m03"
    m03.vm.network "private_network", ip: "192.180.0.103"
    m03.vm.provider "virtualbox" do |v|
      v.name = "m03"
      v.memory = 4096
    end
  end


  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
